fix bilibili
erickguan/discourse-chinese-localization-pack pull request #12
Opened 2022-03-17 08:55 UTC by scavin

2022-08-07 14:36 UTC, erickguan requested changes

2022-08-07 14:36 UTC, erickguan commented on lib/onebox/bilibili.rb
> +        "<iframe src='https://player.bilibili.com/player.html?bvid=#{video_id}\&high_quality=1' frameborder='no' width='100%' height='430' allowfullscreen='true'></iframe>"
`        "<iframe src='https://player.bilibili.com/player.html?#{video_id}&high_quality=1' frameborder='no' width='100%' height='430' allowfullscreen='true'></iframe>"
`

2022-08-07 14:40 UTC, erickguan commented on lib/onebox/bilibili.rb
> +        return "bvid=#{match[1]}" if match && match[1]
bv是什么链接？这个需要么？ https://github.com/erickguan/discourse-chinese-localization-pack/pull/11/files#diff-61db59dde457180618a0ead6667acf255171ab01f6bc86c507d99a9ee1874cfdR13

2022-08-08 08:20 UTC, scavin commented on lib/onebox/bilibili.rb
> +        return "bvid=#{match[1]}" if match && match[1]
手上木有测试环境，近期的还未完成测试。

2022-08-08 20:21 UTC, erickguan commented on lib/onebox/bilibili.rb
> +        return "bvid=#{match[1]}" if match && match[1]
Okay，需要的话我可以接手改了

2022-08-09 05:40 UTC, scavin commented on lib/onebox/bilibili.rb
> +        return "bvid=#{match[1]}" if match && match[1]
等我这两天找时间重建测一下

2022-08-09 06:11 UTC, scavin commented on lib/onebox/bilibili.rb
> +        return "bvid=#{match[1]}" if match && match[1]
测试成功了，之前的提交撤回了，，可以接手改掉了。


之前遇到的问题是 B 站视频链接结尾带了 /，导致这样的错误：

```
https://player.bilibili.com/player.html?bvid=BV16F411c7Y5/&high_quality=1
https://player.bilibili.com/player.html?bvid=BV16F411c7Y5&high_quality=1
```

但我测试那个正则似乎没问题，发帖时去掉 / 就好了。不过 B 站默认并没有 /

2022-08-16 18:09 UTC, erickguan commented on lib/onebox/bilibili.rb
> +      matches_regexp(/^https?:\/\/(?:www\.)?bilibili\.com\/video\/([A-z0-9]+)\/?$/)
`matches_regexp(/^https?:\/\/(?:www\.)?bilibili\.com\/video\/([A-Za-z0-9]+)\/?$/)`

2022-08-16 18:09 UTC, erickguan commented on lib/onebox/bilibili.rb
> +        return "bvid=#{match[1]}" if match && match[1]
恩，好的。那我周末修改完合并了

2022-09-04 15:04 UTC, erickguan commented
https://github.com/erickguan/discourse-chinese-localization-pack/pull/13 测试一下？

2022-09-05 01:40 UTC, scavin commented
> #13 测试一下？

没问题了。说明可以改一下 2.9.0.beta9 测试成功

2022-09-06 21:13 UTC, closed without merging